name: Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium

      - name: Run Selenium tests
        env:
          SELENIUM_REMOTE_URL: http://localhost:4444/wd/hub
        run: |
          python test_selenium.py

      - name: Deploy to Staging Server
        if: success()
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER: ${{ secrets.STAGING_SERVER }}
          USER: ${{ secrets.STAGING_USER }}
        run: |
          ssh -i $SSH_PRIVATE_KEY $USER@$SERVER "cd /path/to/staging && git pull origin staging && npm install && npm run build"

      - name: Post-Deployment Monitoring
        run: |
          sleep 30 # Подождать, пока сервисы поднимутся
          curl -X GET http://your-staging-site-url.com/health-check
        continue-on-error: true

      - name: Check Monitoring Status
        id: check_status
        run: echo "status=$(curl -s http://your-staging-site-url.com/health-check | jq .status)" >> $GITHUB_ENV

      - name: Rollback if Monitoring Fails
        if: ${{ env.status != 'healthy' }}
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER: ${{ secrets.STAGING_SERVER }}
          USER: ${{ secrets.STAGING_USER }}
        run: |
          ssh -i $SSH_PRIVATE_KEY $USER@$SERVER "cd /path/to/staging && git reset --hard HEAD~1 && npm install && npm run build"
